-- -------------------------
-- PROCESADORES INICIALES --
-- -------------------------
INSERT INTO `processors` (`id`, `invert`, `decimals`, `icon`, `name`, `method`, `country`, `currency`, `status_buy`, `status_sell`) VALUES
('bank-bol-banco-union', 0, 2, '671c10d69b9cf.png', 'Banco Unión', 'bank', 'bol', 'bob', 'active', 'active'),
('bank-bra-santander', 0, 2, '671c0d6926878.png', 'Santander', 'bank', 'bra', 'brl', 'active', 'active'),
('bank-chl-banco-de-chile', 0, 2, '671bf7e25d9a3.png', 'Banco de Chile', 'bank', 'chl', 'clp', 'active', 'active'),
('bank-chl-banco-estado', 0, 2, '671bf7beb38d6.png', 'Banco Estado', 'bank', 'chl', 'clp', 'active', 'active'),
('bank-chl-santander', 0, 2, '671bf80d700df.png', 'Santander', 'bank', 'chl', 'clp', 'active', 'active'),
('bank-col-bancolombia', 1, 2, '671bbe276aaac.png', 'Bancolombia', 'bank', 'col', 'cop', 'active', 'active'),
('bank-col-davivienda', 1, 2, '671bbe3faa5f6.png', 'Davivienda', 'bank', 'col', 'cop', 'active', 'active'),
('bank-cri-bac-san-jose', 0, 2, '671c0cc48df09.png', 'BAC San José', 'bank', 'cri', 'crc', 'active', 'active'),
('bank-cri-banco-nacional', 0, 2, '671c0cd023373.png', 'Banco Nacional', 'bank', 'cri', 'crc', 'active', 'active'),
('bank-cri-bcr', 0, 2, '671c0cdae3060.png', 'BCR', 'bank', 'cri', 'crc', 'active', 'active'),
('bank-dom-banco-del-progreso', 0, 2, '671c0af1536c2.png', 'Banco del Progreso', 'bank', 'dom', 'dop', 'active', 'active'),
('bank-dom-banco-popular', 0, 2, '671c0a5879944.png', 'Banco Popular', 'bank', 'dom', 'dop', 'active', 'active'),
('bank-dom-banco-santa-cruz', 0, 2, '671c0b101498e.png', 'Banco Santa Cruz', 'bank', 'dom', 'dop', 'active', 'active'),
('bank-dom-banreservas', 0, 2, '671c0a3c2a9ea.png', 'BanReservas', 'bank', 'dom', 'dop', 'active', 'active'),
('bank-dom-bhd-leon', 0, 2, '671c0acd20da3.png', 'BHD León', 'bank', 'dom', 'dop', 'active', 'active'),
('bank-dom-scotiabank', 0, 2, '671c0b293fe4d.png', 'Scotiabank', 'bank', 'dom', 'dop', 'active', 'active'),
('bank-ecu-banco-guayaquil', 0, 2, '671bfcb044f9c.png', 'Banco Guayaquil', 'bank', 'ecu', 'usd', 'active', 'active'),
('bank-ecu-banco-pichincha', 0, 2, '671bfc7cdcf71.png', 'Banco Pichincha', 'bank', 'ecu', 'usd', 'active', 'active'),
('bank-ecu-produbanco', 0, 2, '671bfcc92703a.png', 'Produbanco', 'bank', 'ecu', 'usd', 'active', 'active'),
('bank-esp-abanca', 0, 2, '671c0545b24f6.png', 'Abanca', 'bank', 'esp', 'eur', 'active', 'active'),
('bank-esp-bankia', 0, 2, '671c057f693d5.png', 'Bankia', 'bank', 'esp', 'eur', 'active', 'active'),
('bank-esp-bbva', 0, 2, '671c059f3b6d0.png', 'BBVA', 'bank', 'esp', 'eur', 'active', 'active'),
('bank-esp-caixabank', 0, 2, '671c05b139d1a.png', 'CaixaBank', 'bank', 'esp', 'eur', 'active', 'active'),
('bank-esp-cajamar', 0, 2, '671c066b6d5f9.png', 'Cajamar', 'bank', 'esp', 'eur', 'active', 'active'),
('bank-esp-ing', 0, 2, '671c05c249733.png', 'ING', 'bank', 'esp', 'eur', 'active', 'active'),
('bank-esp-liberbank', 0, 2, '671c063824f8d.png', 'Liberbank', 'bank', 'esp', 'eur', 'active', 'active'),
('bank-esp-santander', 0, 2, '671c06483463c.png', 'Santander', 'bank', 'esp', 'eur', 'active', 'active'),
('bank-mex-bancoppel', 0, 2, '671c035b19d8b.png', 'BanCoppel', 'bank', 'mex', 'mxn', 'active', 'active'),
('bank-mex-banregio', 0, 2, '671c03515580d.png', 'BanRegio', 'bank', 'mex', 'mxn', 'active', 'active'),
('bank-mex-scotiabank', 0, 2, '671c0267f399d.png', 'Scotiabank', 'bank', 'mex', 'mxn', 'active', 'active'),
('bank-pan-banco-general', 0, 2, '671bc1c106073.png', 'Banco General', 'bank', 'pan', 'pab', 'active', 'active'),
('bank-pan-banesco', 0, 2, '671bc1cde5cc3.png', 'Banesco', 'bank', 'pan', 'pab', 'active', 'active'),
('bank-pan-mercantil', 0, 2, '671bc1da4a323.png', 'Mercantil', 'bank', 'pan', 'pab', 'active', 'active'),
('bank-per-bbva', 0, 2, '671bfa76e9297.png', 'BBVA', 'bank', 'per', 'pen', 'active', 'active'),
('bank-per-bcp', 0, 2, '671bfa83aba2b.png', 'BCP', 'bank', 'per', 'pen', 'active', 'active'),
('bank-per-interbank', 0, 2, '671bfa917953f.png', 'Interbank', 'bank', 'per', 'pen', 'active', 'active'),
('bank-per-scotiabank', 0, 2, '671bfb1b406ab.png', 'Scotiabank', 'bank', 'per', 'pen', 'active', 'active'),
('bank-prt-novo-banco', 0, 2, '671c081219c57.png', 'Novo Banco', 'bank', 'prt', 'eur', 'active', 'active'),
('bank-ury-banco-itau', 0, 2, '671c0f5bbc204.png', 'Banco Itaú', 'bank', 'ury', 'uyu', 'active', 'active'),
('bank-ury-banco-santander', 0, 2, '671c0f722837e.png', 'Banco Santander', 'bank', 'ury', 'uyu', 'active', 'active'),
('bank-usa-bank-of-america', 0, 2, '671bc43bc3a93.png', 'Bank of America', 'bank', 'usa', 'usd', 'active', 'active'),
('bank-ven-banco-de-venezuela', 0, 2, '671bb5c8d86df.png', 'Banco de Venezuela', 'bank', 'ven', 'ves', 'active', 'active'),
('bank-ven-banesco', 0, 2, '671bb616772f5.png', 'Banesco', 'bank', 'ven', 'ves', 'active', 'active'),
('bank-ven-mercantil', 0, 2, '671bb62950ad6.png', 'Mercantil', 'bank', 'ven', 'ves', 'active', 'active'),
('bank-ven-provincial', 0, 2, '671bb63a07425.png', 'Provincial', 'bank', 'ven', 'ves', 'active', 'active'),
('card-col-datafono-digital', 1, 2, '671bbbb9c7257.png', 'Datáfono Digital', 'card', 'col', 'cop', 'active', 'active'),
('cash-arg-western-union', 0, 2, '671c01600b2f0.png', 'Western Union', 'cash', 'arg', 'ars', 'active', 'active'),
('cash-bol-western-union', 0, 2, '671c0fead8754.png', 'Western Union', 'cash', 'bol', 'bob', 'active', 'active'),
('cash-bra-western-union', 0, 2, '671c0d4ea2e62.png', 'Western Union', 'cash', 'bra', 'brl', 'active', 'active'),
('cash-chl-western-union', 0, 2, '671bf71f7b9ca.png', 'Western Union', 'cash', 'chl', 'clp', 'active', 'active'),
('cash-col-efectivo', 1, 2, '671bbe5ad6a38.png', 'Efectivo', 'cash', 'col', 'cop', 'active', 'active'),
('cash-col-efecty', 1, 2, '671bbe68cef4c.png', 'Efecty', 'cash', 'col', 'cop', 'active', 'active'),
('cash-col-western-union', 1, 2, '671bc272d9cb4.png', 'Western Union', 'cash', 'col', 'cop', 'active', 'active'),
('cash-cri-western-union', 0, 2, '671c0b929bb5e.png', 'Western Union', 'cash', 'cri', 'crc', 'active', 'active'),
('cash-ecu-western-union', 0, 2, '671bfce2613a8.png', 'Western Union', 'cash', 'ecu', 'usd', 'active', 'active'),
('cash-esp-western-union', 0, 2, '671c06dcc8dc0.png', 'Western Union', 'cash', 'esp', 'eur', 'active', 'active'),
('cash-mex-oxxo', 0, 2, '671c034481eb3.png', 'OXXO', 'cash', 'mex', 'mxn', 'active', 'active'),
('cash-mex-western-union', 0, 2, '671c022e5d9dd.png', 'Western Union', 'cash', 'mex', 'mxn', 'active', 'active'),
('cash-pan-western-union', 0, 2, '671bc0e82f318.png', 'Western Union', 'cash', 'pan', 'pab', 'active', 'active'),
('cash-per-western-union', 0, 2, '671bf8e933a43.png', 'Western Union', 'cash', 'per', 'pen', 'active', 'active'),
('cash-prt-western-union', 0, 2, '671c078c77d4c.png', 'Western Union', 'cash', 'prt', 'eur', 'active', 'active'),
('cash-ury-western-union', 0, 2, '671c0ea8e0b95.png', 'Western Union', 'cash', 'ury', 'uyu', 'active', 'active'),
('cash-usa-western-union', 0, 2, '671bc47089348.png', 'Western Union', 'cash', 'usa', 'usd', 'active', 'active'),
('cash-ven-avance-efectivo-usd', 0, 2, '671c1345b5775.png', 'Avance Efectivo USD', 'cash', 'ven', 'usd', 'active', 'active'),
('mobile-bol-tigo-money', 0, 2, '671c10ea83703.png', 'Tigo Money', 'mobile', 'bol', 'bob', 'active', 'active'),
('mobile-bra-pix', 0, 2, '671c0dbfe67a4.png', 'Pix', 'mobile', 'bra', 'brl', 'active', 'active'),
('mobile-col-daviplata', 1, 2, '671bbe7ca488f.png', 'Daviplata', 'mobile', 'col', 'cop', 'active', 'active'),
('mobile-col-movii', 1, 2, '671bbe8eb92c6.png', 'Movii', 'mobile', 'col', 'cop', 'blocked', 'blocked'),
('mobile-col-nequi', 1, 2, '671bbe9b6a2f7.png', 'Nequi', 'mobile', 'col', 'cop', 'active', 'active'),
('mobile-col-transfiya', 1, 2, '671bf8926d56d.png', 'Transfiya', 'mobile', 'col', 'cop', 'active', 'active'),
('mobile-esp-bizum', 0, 2, '671c06fa7efee.png', 'Bizum', 'mobile', 'esp', 'eur', 'active', 'active'),
('mobile-pan-mony', 0, 2, '671bc1f06aae7.png', 'Mony', 'mobile', 'pan', 'pab', 'active', 'active'),
('mobile-pan-yappy', 0, 2, '671bc1fb46e1a.png', 'Yappy', 'mobile', 'pan', 'pab', 'active', 'active'),
('mobile-per-yape', 0, 2, '671bfb2c6cd5a.png', 'Yape', 'mobile', 'per', 'pen', 'active', 'active'),
('mobile-ury-mi-dinero', 0, 2, '671c0f2dd23f7.png', 'Mi Dinero', 'mobile', 'ury', 'uyu', 'active', 'active'),
('mobile-ury-prex', 0, 2, '671c0f3b49d74.png', 'Prex', 'mobile', 'ury', 'uyu', 'active', 'active'),
('mobile-usa-zelle', 0, 2, '671bc456e20ba.png', 'Zelle', 'mobile', 'usa', 'usd', 'active', 'active'),
('mobile-ven-pago-movil', 0, 2, '671bb65117362.png', 'Pago Móvil', 'mobile', 'ven', 'ves', 'active', 'active'),
('platform-per-bcp-giros', 0, 2, '671bfa64cb341.png', 'BCP Giros', 'platform', 'per', 'pen', 'active', 'active'),
('wallet-airtm', 0, 2, '671c1335375e2.png', 'Airtm', 'wallet', NULL, 'usd', 'active', 'active'),
('wallet-arg-lemon-cash', 0, 2, '671c01313392e.png', 'Lemon Cash', 'wallet', 'arg', 'ars', 'active', 'active'),
('wallet-arg-naranja-x', 0, 2, '671c01027d933.png', 'Naranja X', 'wallet', 'arg', 'ars', 'active', 'active'),
('wallet-arg-uala', 0, 2, '671c019214f52.png', 'Uala', 'wallet', 'arg', 'ars', 'active', 'active'),
('wallet-binance', 0, 2, '671c1472eca51.png', 'Binance', 'wallet', NULL, 'usdt', 'active', 'active'),
('wallet-payoneer', 0, 2, '671c1351c1859.png', 'Payoneer', 'wallet', NULL, 'usd', 'active', 'active'),
('wallet-paypal', 0, 2, '671c135e0eb68.png', 'PayPal', 'wallet', NULL, 'usd', 'active', 'active'),
('wallet-skrill', 0, 2, '671c13267c13d.png', 'Skrill', 'wallet', NULL, 'usd', 'active', 'active'),
('wallet-uphold', 0, 2, '671c1319f3dda.png', 'Uphold', 'wallet', NULL, 'usd', 'active', 'active');